modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/JamCoreModding/jamlib/issues"

[[mods]]
modId = "jamlib"
version = "${file.jarVersion}"
displayName = "JamLib"
displayURL = "https://github.com/JamCoreModding/jamlib"
logoFile = "icon.png"
authors = "Jamalam"
description = '''The platform-agnostic library used in all of JamCore's mods'''

[[dependencies.jamlib]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jamlib]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.jamlib]]
modId = "architectury"
type = "required"
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"
