modLoader = "javafml"
loaderVersion = "[47,)"
license = "MIT"
issueTrackerURL = "https://github.com/JamCoreModding/jamlib/issues"

[[mods]]
modId = "testmod"
version = "${file.jarVersion}"
displayName = "JamLib Test Mod"
displayURL = "https://github.com/JamCoreModding/jamlib"
logoFile = "icon.png"
authors = "Jamalam"
description = '''
Test Mod for JamLib
'''

[[dependencies.testmod]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.testmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.testmod]]
modId = "architectury"
mandatory = true
versionRange = "[9.1.12,)"
ordering = "AFTER"
side = "BOTH"
